---
kind: pipeline
type: docker
name: push-latest
steps:
- name: build-and-push
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  branch:
  - master
  event:
    exclude:
    - pull_request
---
kind: pipeline
type: docker
name: push-release
steps:
- name: build-and-push-tag
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    tags: ${DRONE_TAG##v} # strips v from the tag
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  event:
  - tag
---
kind: pipeline
type: docker
name: dry-run
steps:
- name: dry-run
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    dry_run: true
trigger:
  event:
  - pull_request
---
kind: secret
name: docker_username
data: YMRGXQO8h9dvl03mQcMD7j/zqai5Jv4/9T4GWGV0h3vKd/rSyv615Q==
---
kind: secret
name: docker_password
data: zhe0n+7A5pFDZNJtV2rjGg77jGQdG/DDe5nXcMi21++qcZfAxVOzUjn+PKcT5pAez8LqCXur9+IkVd+nNDv5Jw==
---
kind: signature
hmac: 7d204bb2b2b1656f8187dc29a651ecf0493a631d77a293b90cd14e99a62065c6

...
